# Generated by Django 2.1 on 2018-08-31 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaming_id', models.CharField(max_length=16)),
                ('platform', models.CharField(choices=[('ps4', 'PlayStation 4'), ('xbo', 'Xbox One')], default='ps4', max_length=13)),
                ('gamerstyle', models.CharField(choices=[('casual', 'Competititor'), ('moderate', 'Moderate'), ('hardcore', 'Hardcore')], default='casual', max_length=13)),
                ('playstyle', models.CharField(choices=[('adventurer', 'Adventurer'), ('competitor', 'Competititor'), ('hunter', 'Hunter'), ('level_grinder', 'Level Grinder'), ('money_maker', 'Money Maker'), ('royale_fiend', 'Royale Fiend')], default='adventurer', max_length=13)),
                ('message', models.TextField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
