# Generated by Django 2.1 on 2018-08-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr2_fellas', '0002_auto_20180831_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='message',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='day_availability',
            field=models.CharField(choices=[('Every Day', 'Every Day'), ('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], default='Every Day', max_length=13),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_availability',
            field=models.CharField(choices=[('Any Time', 'Any Time'), ('Morning', 'Morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Any Time', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gamerstyle',
            field=models.CharField(choices=[('Casual', 'Competititor'), ('Moderate', 'Moderate'), ('Hardcore', 'Hardcore')], default='Casual', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(choices=[('PlayStation 4', 'PlayStation 4'), ('Xbox One', 'Xbox One')], default='PlayStation 4', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='playstyle',
            field=models.CharField(choices=[('Adventurer', 'Adventurer'), ('Competitor', 'Competititor'), ('Hunter', 'Hunter'), ('Level Grinder', 'Level Grinder'), ('Money Maker', 'Money Maker'), ('Royale Fiend', 'Royale Fiend')], default='Adventurer', max_length=13),
        ),
    ]
