# Generated by Django 2.1 on 2018-09-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr2_fellas', '0003_auto_20180831_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gamerstyle',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Moderate', 'Moderate'), ('Hardcore', 'Hardcore')], default='Casual', max_length=13),
        ),
    ]
